# Macro file for RUN21 (GENBOS)
#
# To be run preferably in batch, without graphics:
# % run21_geant4_2 run2.mac
#

#/run/numberOfThreads 4
#/control/cout/ignoreThreadsExcept 0
#


/run/initialize
#/gun/GenbosBool 1
/gun/random on
/gun/count on
/gun/CStep 10000
#/gun/mode 34
#/gun/mode 3
#/gun/mode 8
/gun/EgMin 400 MeV
/gun/EgMax 650 MeV
#/tracking/storeTrajectory 0
/run/printProgress 10000
/run/beamOn 2000000
#/run/beamOn 40000
