# Macro file for example Cosmic
# 
# To be run preferably in batch, without graphics:
# % exampleCosmic[a,b,c,d] run2.mac
#
#/run/numberOfThreads 4
#/control/cout/ignoreThreadsExcept 0
#
/run/initialize
#
# Default kinemtics: 
# electron 50 MeV in direction (0.,0.,1.)
# 1000 events
#

/run/verbose 0
/particle/verbose 0
/particle/property/verbose 0
/event/verbose 0
/run/particle/verbose 0


/run/printProgress 1000
/run/beamOn 20000

